### PR TITLE
Update exception handling

### PR DESCRIPTION
**Pull request by anthropos9**
Updated the Guzzle requests in the Client object so that they were wrapped in try/catch blocks to catch Guzzle exceptions and throw the appropriate Geocodio exception. Removed the checkResponse method since it was no longer needed. Updated exceptions to use the global Exception object's constructor so that they can be handled within apps using the library. Also updated the namespaces on the exceptions.

### CODE REVIEW

**Comment by MiniCodeMonkey** [comment]
Hi there,

Thanks a ton for contributing with this.

This is causing some merge conflicts after merging in https://github.com/Geocodio/geocodio-php/pull/17 - do you mind resolving those conflicts?

Happy to merge this in when the conflicts have been resolved.

Mathias

**Comment by MiniCodeMonkey** [comment]
Uoops, didn't mean to close the PR. Sorry!

**Comment by MichaelT372** [comment]
Hi, is the status on this that it still needs merge conflicts resolving? It'd be great to get merged as in the current code Guzzle will throw uncaught exceptions on failed requests.

**Comment by MiniCodeMonkey** [comment]
Thanks for bumping this! I have resolved the conflicts and merged in the changes. v1.9.0 has been released with these changes.

**Comment by MichaelT372** [comment]
Thank you!

**Pull request merged**
