### PR TITLE
When reverse geocoding, we have to set the right verb

### PR DESCRIPTION
**Pull request by joshuaziering**
Otherwise all our stuff comes back as "unable to geocode"

Please merge this asap as nobody can reverse geocode without this :(

### CODE REVIEW

**Comment by MiniCodeMonkey** [comment]
@joshuaziering Please use the `reverse()` function directly, and pass in an array.

I've updated the documentation to clarify this use case:
https://github.com/Geocodio/geocodio-php#reverse-geocoding-multiple-coordinates

**Comment by joshuaziering** [comment]
I am using the reverse function directly. Im passing it an array of strings that looks like this:

screen shot 2017-06-26 at 4 16 06 pm

And the result certainly looks like it's using the wrong verb ... 

screen shot 2017-06-26 at 4 16 40 pm

Because in Paw, I get really nice results for those lat/longs.

screen shot 2017-06-26 at 4 16 55 pm

My pull request fixes a bug in the library, I'm not trying to use it directly, but it doesn't work as expected.

**Comment by joshuaziering** [comment]
And when I use the change outlined in the pull request, I get these nice results:

screen shot 2017-06-26 at 4 29 13 pm

**Comment by joshuaziering** [comment]
@MiniCodeMonkey Can you take a look at this one more time please?

**Pull request closed without merging**
